name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        id: spelling
        with:
          config: '.github/workflows/cspell.json'
          files: '**/*.md'
          incremental_files_only: true
